import { Raydium, CurveCalculator } from "@raydium-io/raydium-sdk-v2";
import BN from "bn.js";
import { getConnection } from "../utils/get-rpc";
import { getKeypair } from "../utils/get-keypair";
import { getSymbol } from "../utils/get-symbol";
import dotenv from "dotenv";

dotenv.config();

function formatTokenAmount(amount: BN, decimals: number): string {
    return (amount.toNumber() / 10 ** decimals).toLocaleString(undefined, {
        maximumFractionDigits: decimals,
    });
}

async function getCpmmPoolPrice(poolIdStr: string) {
    const connection = getConnection("devnet");
    const owner = getKeypair();

    const raydium = await Raydium.load({
        owner,
        connection,
        // cluster: "devnet",
        disableFeatureCheck: true,
    });

    console.log(`Fetching Devnet RPC state for Pool: ${poolIdStr}...`);
    
    // Fetch live pool info directly from the blockchain state (crucial for Devnet)
    const { poolInfo, rpcData } = await raydium.cpmm.getPoolInfoFromRpc(poolIdStr);

    // Extract reserves and decimals
    const baseReserveRaw = rpcData.baseReserve.toNumber();
    const quoteReserveRaw = rpcData.quoteReserve.toNumber();

    const baseDecimals = poolInfo.mintA.decimals;
    const quoteDecimals = poolInfo.mintB.decimals;

    // Convert raw lamports/atoms to human-readable format
    const baseReserve = baseReserveRaw / Math.pow(10, baseDecimals);
    const quoteReserve = quoteReserveRaw / Math.pow(10, quoteDecimals);

    const symbolA = getSymbol(poolInfo.mintA.address) ?? poolInfo.mintA.symbol;
    const symbolB = getSymbol(poolInfo.mintB.address) ?? poolInfo.mintB.symbol;

    // Constant Product Price Math
    const priceAInB = quoteReserve / baseReserve;
    const priceBInA = baseReserve / quoteReserve;

    console.log("\n📊 --- POOL STATE ---");
    console.log(`Pool Pair: ${symbolA} / ${symbolB}`);
    console.log(`Base Asset (${symbolA}) Reserve: ${baseReserve.toLocaleString()}`);
    console.log(`Quote Asset (${symbolB}) Reserve: ${quoteReserve.toLocaleString()}`);
    // console.log("----------------------");
    // console.log(`💡 SPOT:  1 ${symbolA} = ${priceAInB.toFixed(6)} ${symbolB}`);
    // console.log(`💡 SPOT:  1 ${symbolB} = ${priceBInA.toFixed(6)} ${symbolA}`);

    const config = rpcData.configInfo;
    if (config) {
        const oneBaseToken = new BN(10 ** baseDecimals);
        const oneQuoteToken = new BN(10 ** quoteDecimals);
        const isCreatorFeeOnInput = rpcData.feeOn === 0 || rpcData.feeOn === 2;

        const swapAtoB = CurveCalculator.swapBaseInput(
            oneBaseToken,
            rpcData.baseReserve,
            rpcData.quoteReserve,
            config.tradeFeeRate,
            config.creatorFeeRate,
            config.protocolFeeRate,
            config.fundFeeRate,
            isCreatorFeeOnInput,
        );

        const swapBtoA = CurveCalculator.swapBaseInput(
            oneQuoteToken,
            rpcData.quoteReserve,
            rpcData.baseReserve,
            config.tradeFeeRate,
            config.creatorFeeRate,
            config.protocolFeeRate,
            config.fundFeeRate,
            isCreatorFeeOnInput,
        );

        const swapRateAInB = swapAtoB.outputAmount.toNumber() / 10 ** quoteDecimals;
        const swapRateBInA = swapBtoA.outputAmount.toNumber() / 10 ** baseDecimals;

        console.log("----------------------");
        console.log(`💡 SWAP:  1 ${symbolA} -> ${formatTokenAmount(swapAtoB.outputAmount, quoteDecimals)} ${symbolB}  (fee: ${formatTokenAmount(swapAtoB.tradeFee, baseDecimals)} ${symbolA})`);
        console.log(`         vs spot: ${priceAInB.toFixed(6)} ${symbolB}  (diff: ${(priceAInB - swapRateAInB).toFixed(6)} ${symbolB})`);
        console.log(`💡 SWAP:  1 ${symbolB} -> ${formatTokenAmount(swapBtoA.outputAmount, baseDecimals)} ${symbolA}  (fee: ${formatTokenAmount(swapBtoA.tradeFee, quoteDecimals)} ${symbolB})`);
        console.log(`         vs spot: ${priceBInA.toFixed(6)} ${symbolA}  (diff: ${(priceBInA - swapRateBInA).toFixed(6)} ${symbolA})`);
    }
}

// Replace this with the Pool ID string generated by your creation script
const TARGET_POOL_ID = process.env.POOL_ID ?? "FKzvtrxbd1SBn7DrnmbWqA2HB2NiH7PJmVehHVnCHn79"; 
getCpmmPoolPrice(TARGET_POOL_ID).catch(console.error);
